		CREATE TABLE IF NOT EXISTS pessoa(
		id BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
		nome VARCHAR(50) NOT NULL,
		idade VARCHAR(20) NOT NULL,
		sexo VARCHAR(10) NOT NULL,
		grupo VARCHAR(20) NOT NULL
		)ENGINE=InnODB DEFAULT CHARSET=UTF8;